### ISSUE TITLE
little suggestion: skip output of the chunk asset

### ISSUE THREAD

**Issue by 3gogo** [KyLeoHC/inline-source-webpack-plugin#1]
As label mentions I got some unnecessary files after run build. If I can choose which file to remain or not it will be more pleasant . thanks a lot~

**Comment by KyLeoHC** [comment]
#2b25ac315f53665d4a7c5c7958eb2a9cfeed077b

**Comment by KyLeoHC** [comment]
#https://github.com/KyLeoHC/inline-source-webpack-plugin/commit/2b25ac315f53665d4a7c5c7958eb2a9cfeed077b
