### ISSUE TITLE
ERROR in Unexpected token: punc (.) when trying to compress ES6 JS

### ISSUE THREAD

**Issue by zubozrout** [KyLeoHC/inline-source-webpack-plugin#18]
Hi,
I've been trying to use your plugin to compile multiple files into one HTML.

However, when I have `compress: true` in the webpack config for your plugin I am getting `Unexpected token: punc (.)` error.
For now I can do without that compression, however it would be nice to have support for that.

I suppose this is the same thing I am experiencing: https://stackoverflow.com/questions/42375468/uglify-syntaxerror-unexpected-token-punc

Is there a way to workaround that perhaps using uglify directly and passing that to `InlineSourceWebpackPlugin` or is support for ES6 planned?

Here is my complete webpack config file: [webpack.config.mjs.txt](https://github.com/KyLeoHC/inline-source-webpack-plugin/files/7564395/webpack.config.mjs.txt)

Thank you very much.
Best regards,
Martin

**Comment by KyLeoHC** [comment]
I use terser library instead of Uglify plugin. Can you show me your code for debug?

**Comment by zubozrout** [comment]
Hello @KyLeoHC, thank you very much for your response. I do apologize for the yesterday's report - it was not comprehensive enough as I had not more time to test this.

Anyway, I've now been able to track it down to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining which is not ES6 (I've taken it a bit too far). Therefore I do very much apologize for this report.

Nonetheless it looks like it is already supported by Terser: https://github.com/terser/terser/issues/567#issuecomment-675583347 so if you'd be able to add support for this as well it would be gorgeous.

Nonetheless this but report is no longer relevant as per the title so please feel free to close it whenever it suits you :).
Thank you very much.

**Comment by KyLeoHC** [comment]
@zubozrout Ok.It seems that I'd better upgrade terser.I will fix it.

**Comment by zubozrout** [comment]
Thank you very much @KyLeoHC. Works like a charm for me now :)
